# Generated by Django 3.2.11 on 2022-06-09 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120, unique=True)),
                ('address', models.CharField(max_length=120)),
                ('phone', models.PositiveIntegerField(default=50)),
                ('date', models.DateField(auto_now_add=True, null=True)),
            ],
        ),
    ]
